name = "fastcraft-api"
main = "src/index.js"
compatibility_date = "2026-01-01"

# Routes pour intercepter l'API et TOUS les sous-domaines
routes = [
  { pattern = "api.fastcraft.uk/*", zone_name = "fastcraft.uk" },
  { pattern = "*.fastcraft.uk/*", zone_name = "fastcraft.uk" }
]

# Binding à la base de données D1
[[d1_databases]]
binding = "DB"
database_name = "fastcraft-db"
database_id = "cf66cdd0-ad3c-4517-ba8b-e026fd8d493a"
